# Generated by Django 5.2.7 on 2025-11-05 12:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blacklistedtoken_auditlog_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48)),
                ('name', models.CharField(max_length=180)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('usage', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('pos', 'POS')], default='sales', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.productcategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('track_inventory', models.BooleanField(default=True)),
                ('allow_backorder', models.BooleanField(default=False)),
                ('attributes_schema', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.productcategory')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=180)),
                ('barcode', models.CharField(blank=True, max_length=80)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('conversion_factor', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=16)),
                ('cost_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('sales_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('track_inventory', models.BooleanField(default=True)),
                ('allow_backorder', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
            options={
                'ordering': ('sku',),
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12)),
                ('price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.pricelist')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_items', to='api.productvariant')),
            ],
            options={
                'ordering': ('price_list', 'variant'),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48)),
                ('name', models.CharField(max_length=180)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('mobile', models.CharField(blank=True, max_length=32)),
                ('website', models.URLField(blank=True)),
                ('tax_number', models.CharField(blank=True, max_length=64)),
                ('payment_terms', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('billing_address', models.JSONField(blank=True, default=dict)),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('rate', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('scope', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('both', 'Both')], default='both', max_length=12)),
                ('is_inclusive', models.BooleanField(default=False)),
                ('is_compound', models.BooleanField(default=False)),
                ('account_code', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='default_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.tax'),
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('symbol', models.CharField(blank=True, max_length=12)),
                ('category', models.CharField(choices=[('quantity', 'Quantity'), ('weight', 'Weight'), ('volume', 'Volume'), ('length', 'Length'), ('time', 'Time'), ('custom', 'Custom')], default='quantity', max_length=20)),
                ('conversion_factor', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=16)),
                ('is_decimal', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_units', to='api.unitofmeasure')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sales_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants_as_sales_uom', to='api.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='product',
            name='base_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_as_base', to='api.unitofmeasure'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WarehouseBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48)),
                ('name', models.CharField(max_length=160)),
                ('bin_type', models.CharField(choices=[('storage', 'Storage'), ('receiving', 'Receiving'), ('shipping', 'Shipping'), ('picking', 'Picking'), ('returns', 'Returns')], default='storage', max_length=16)),
                ('is_default', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='api.warehouse')),
            ],
            options={
                'ordering': ('warehouse', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48)),
                ('name', models.CharField(max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('mobile', models.CharField(blank=True, max_length=32)),
                ('website', models.URLField(blank=True)),
                ('tax_number', models.CharField(blank=True, max_length=64)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('billing_address', models.JSONField(blank=True, default=dict)),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['tenant', 'code'], name='api_custome_tenant__b43155_idx'), models.Index(fields=['tenant', 'is_active'], name='api_custome_tenant__51c403_idx')],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.AddIndex(
            model_name='pricelist',
            index=models.Index(fields=['tenant', 'code'], name='api_priceli_tenant__6e7f93_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelist',
            index=models.Index(fields=['tenant', 'usage'], name='api_priceli_tenant__729d51_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelist',
            index=models.Index(fields=['tenant', 'is_default'], name='api_priceli_tenant__71b2eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelist',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['tenant', 'name'], name='api_product_tenant__f8735b_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['tenant', 'parent'], name='api_product_tenant__18518b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='pricelistitem',
            index=models.Index(fields=['tenant', 'price_list'], name='api_priceli_tenant__37d207_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelistitem',
            index=models.Index(fields=['tenant', 'variant'], name='api_priceli_tenant__361dae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelistitem',
            unique_together={('tenant', 'price_list', 'variant', 'min_quantity')},
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['tenant', 'code'], name='api_supplie_tenant__c656c9_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['tenant', 'is_active'], name='api_supplie_tenant__42c2ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='tax',
            index=models.Index(fields=['tenant', 'code'], name='api_tax_tenant__9c4f86_idx'),
        ),
        migrations.AddIndex(
            model_name='tax',
            index=models.Index(fields=['tenant', 'scope'], name='api_tax_tenant__842a12_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tax',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='unitofmeasure',
            index=models.Index(fields=['tenant', 'name'], name='api_unitofm_tenant__9ec4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='unitofmeasure',
            index=models.Index(fields=['tenant', 'code'], name='api_unitofm_tenant__401f8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unitofmeasure',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['tenant', 'sku'], name='api_product_tenant__51dd77_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['tenant', 'product'], name='api_product_tenant__d762a0_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['tenant', 'is_active'], name='api_product_tenant__f74ea3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('tenant', 'sku')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'name'], name='api_product_tenant__5215cc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'category'], name='api_product_tenant__5131a5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'is_active'], name='api_product_tenant__bc063d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['tenant', 'code'], name='api_warehou_tenant__763f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['tenant', 'is_default'], name='api_warehou_tenant__bc368f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='warehousebin',
            index=models.Index(fields=['tenant', 'warehouse'], name='api_warehou_tenant__7fde88_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousebin',
            index=models.Index(fields=['tenant', 'bin_type'], name='api_warehou_tenant__2218d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehousebin',
            unique_together={('tenant', 'warehouse', 'code')},
        ),
    ]
