# Generated by Django 5.2.7 on 2025-11-05 12:09

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pricelist_productcategory_product_productvariant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('purchase_receipt', 'Purchase Receipt'), ('purchase_return', 'Purchase Return'), ('sale_shipment', 'Sales Shipment'), ('sale_return', 'Sales Return'), ('adjustment', 'Adjustment'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('pos_sale', 'POS Sale'), ('pos_return', 'POS Return')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], default='posted', max_length=16)),
                ('reference_number', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_document_type', models.CharField(blank=True, max_length=64)),
                ('source_document_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
            options={
                'ordering': ('-performed_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='StockMovementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=16)),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=16)),
                ('value_delta', models.DecimalField(decimal_places=6, max_digits=18)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.stockmovement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movement_lines', to='api.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movement_lines', to='api.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=16)),
                ('value_delta', models.DecimalField(decimal_places=6, max_digits=18)),
                ('running_quantity', models.DecimalField(decimal_places=3, max_digits=16)),
                ('running_value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('average_cost', models.DecimalField(decimal_places=6, max_digits=16)),
                ('reference_type', models.CharField(blank=True, max_length=64)),
                ('reference_id', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='api.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='api.warehouse')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='api.stockmovement')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='api.stockmovementline')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('on_hand', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=16)),
                ('allocated', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=16)),
                ('on_order', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=16)),
                ('average_cost', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('last_movement_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='api.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='api.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'variant'], name='api_invento_tenant__975e5d_idx'), models.Index(fields=['tenant', 'warehouse'], name='api_invento_tenant__d3ecb3_idx')],
                'unique_together': {('tenant', 'variant', 'warehouse')},
            },
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'movement_type'], name='api_stockmo_tenant__c57bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'status'], name='api_stockmo_tenant__7a7f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'performed_at'], name='api_stockmo_tenant__dc3f07_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovementline',
            index=models.Index(fields=['tenant', 'movement'], name='api_stockmo_tenant__b9a3dc_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovementline',
            index=models.Index(fields=['tenant', 'variant'], name='api_stockmo_tenant__ab4bdb_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovementline',
            index=models.Index(fields=['tenant', 'warehouse'], name='api_stockmo_tenant__a1dacc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryledgerentry',
            index=models.Index(fields=['tenant', 'variant'], name='api_invento_tenant__1b4230_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryledgerentry',
            index=models.Index(fields=['tenant', 'warehouse'], name='api_invento_tenant__4d85bc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryledgerentry',
            index=models.Index(fields=['tenant', 'created_at'], name='api_invento_tenant__520053_idx'),
        ),
    ]
