# Generated by Django 5.2.7 on 2025-11-05 12:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_stockmovement_stockmovementline_inventoryledgerentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=48)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('receiving', 'Receiving'), ('received', 'Received'), ('billed', 'Billed'), ('paid', 'Paid'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='api.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
            options={
                'ordering': ('-order_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=48)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('bill_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='api.purchaseorder')),
            ],
            options={
                'ordering': ('-bill_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('ordered_quantity', models.DecimalField(decimal_places=3, max_digits=16)),
                ('received_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=16)),
                ('billed_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=16)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('tax_rate', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.purchaseorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='api.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=16)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('tax_rate', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.purchasebill')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
                ('order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_lines', to='api.purchaseorderline')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=48)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('void', 'Void')], default='posted', max_length=16)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('method', models.CharField(blank=True, max_length=48)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.purchasebill')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=48)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('receipt_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='api.purchaseorder')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_receipts', to=settings.AUTH_USER_MODEL)),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_receipts', to='api.stockmovement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to='api.warehouse')),
            ],
            options={
                'ordering': ('-receipt_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=16)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_lines', to='api.purchaseorderline')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.purchasereceipt')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipt_lines', to='api.productvariant')),
            ],
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant', 'status'], name='api_purchas_tenant__0643c6_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant', 'supplier'], name='api_purchas_tenant__05b5e0_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant', 'order_date'], name='api_purchas_tenant__f0c782_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['tenant', 'status'], name='api_purchas_tenant__8a68e2_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['tenant', 'bill_date'], name='api_purchas_tenant__4dcc2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchasebill',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['tenant', 'order'], name='api_purchas_tenant__c15015_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['tenant', 'variant'], name='api_purchas_tenant__53489b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasebillline',
            index=models.Index(fields=['tenant', 'bill'], name='api_purchas_tenant__d275bd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasepayment',
            index=models.Index(fields=['tenant', 'payment_date'], name='api_purchas_tenant__1b3468_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasepayment',
            index=models.Index(fields=['tenant', 'status'], name='api_purchas_tenant__70b4e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchasepayment',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['tenant', 'status'], name='api_purchas_tenant__626c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['tenant', 'receipt_date'], name='api_purchas_tenant__1ebfce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchasereceipt',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='purchasereceiptline',
            index=models.Index(fields=['tenant', 'receipt'], name='api_purchas_tenant__1eb473_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceiptline',
            index=models.Index(fields=['tenant', 'variant'], name='api_purchas_tenant__7fa996_idx'),
        ),
    ]
