# Generated by Django 5.2.7 on 2025-11-05 12:16

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_purchaseorder_purchasebill_purchaseorderline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=48)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('picking', 'Picking'), ('fulfilled', 'Fulfilled'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='api.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
            options={
                'ordering': ('-order_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=48)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='api.salesorder')),
            ],
            options={
                'ordering': ('-invoice_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=48)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to=settings.AUTH_USER_MODEL)),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='api.stockmovement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='api.warehouse')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.salesorder')),
            ],
            options={
                'ordering': ('-delivery_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('ordered_quantity', models.DecimalField(decimal_places=3, max_digits=16)),
                ('delivered_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=16)),
                ('invoiced_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=16)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('tax_rate', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.salesorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='api.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=16)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('tax_rate', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.salesinvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
                ('order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='api.salesorderline')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=16)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.deliverynote')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_lines', to='api.productvariant')),
                ('order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_lines', to='api.salesorderline')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=48)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('void', 'Void')], default='posted', max_length=16)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('method', models.CharField(blank=True, max_length=48)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.salesinvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SalesRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=48)),
                ('refund_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='api.salesinvoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['tenant', 'status'], name='api_salesor_tenant__be60ad_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['tenant', 'customer'], name='api_salesor_tenant__d37f1e_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['tenant', 'order_date'], name='api_salesor_tenant__ef48be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesorder',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['tenant', 'status'], name='api_salesin_tenant__9d08bd_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['tenant', 'invoice_date'], name='api_salesin_tenant__faa3c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesinvoice',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='deliverynote',
            index=models.Index(fields=['tenant', 'status'], name='api_deliver_tenant__cd64f4_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverynote',
            index=models.Index(fields=['tenant', 'delivery_date'], name='api_deliver_tenant__94ef0a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliverynote',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='salesorderline',
            index=models.Index(fields=['tenant', 'order'], name='api_salesor_tenant__108624_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderline',
            index=models.Index(fields=['tenant', 'variant'], name='api_salesor_tenant__a54de5_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoiceline',
            index=models.Index(fields=['tenant', 'invoice'], name='api_salesin_tenant__88ddeb_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverynoteline',
            index=models.Index(fields=['tenant', 'delivery'], name='api_deliver_tenant__7632b2_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverynoteline',
            index=models.Index(fields=['tenant', 'variant'], name='api_deliver_tenant__07929c_idx'),
        ),
        migrations.AddIndex(
            model_name='salespayment',
            index=models.Index(fields=['tenant', 'payment_date'], name='api_salespa_tenant__bd472f_idx'),
        ),
        migrations.AddIndex(
            model_name='salespayment',
            index=models.Index(fields=['tenant', 'status'], name='api_salespa_tenant__7bee38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salespayment',
            unique_together={('tenant', 'number')},
        ),
        migrations.AddIndex(
            model_name='salesrefund',
            index=models.Index(fields=['tenant', 'refund_date'], name='api_salesre_tenant__3534b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesrefund',
            unique_together={('tenant', 'number')},
        ),
    ]
