# Generated by Django 5.2.7 on 2025-11-05 12:20

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_salesorder_salesinvoice_deliverynote_salesorderline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('register_code', models.CharField(max_length=48)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=16)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_float', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('closing_float', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_shifts_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_shifts_opened', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
            options={
                'ordering': ('-opened_at',),
            },
        ),
        migrations.CreateModel(
            name='POSSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=48)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('void', 'Void')], default='pending', max_length=16)),
                ('subtotal', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('paid_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('change_due', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to='api.customer')),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to='api.stockmovement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sales', to='api.warehouse')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.posshift')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='POSOfflineQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status'], name='api_posoffl_tenant__a2d1e0_idx'), models.Index(fields=['tenant', 'operation'], name='api_posoffl_tenant__35e1b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='POSReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=64)),
                ('rendered_payload', models.JSONField(blank=True, default=dict)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='api.possale')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'number'], name='api_posrece_tenant__0c1049_idx')],
                'unique_together': {('tenant', 'number')},
            },
        ),
        migrations.CreateModel(
            name='POSSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=16)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('discount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('tax_rate', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('line_total', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.possale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sale_items', to='api.productvariant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'sale'], name='api_possale_tenant__cc5e93_idx'), models.Index(fields=['tenant', 'variant'], name='api_possale_tenant__966262_idx')],
            },
        ),
        migrations.CreateModel(
            name='POSSalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('void', 'Void')], default='posted', max_length=16)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.possale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='api.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'sale'], name='api_possale_tenant__f79df7_idx'), models.Index(fields=['tenant', 'method'], name='api_possale_tenant__3e3590_idx'), models.Index(fields=['tenant', 'status'], name='api_possale_tenant__611716_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='posshift',
            index=models.Index(fields=['tenant', 'register_code'], name='api_posshif_tenant__7c3878_idx'),
        ),
        migrations.AddIndex(
            model_name='posshift',
            index=models.Index(fields=['tenant', 'status'], name='api_posshif_tenant__2e764e_idx'),
        ),
        migrations.AddIndex(
            model_name='posshift',
            index=models.Index(fields=['tenant', 'opened_at'], name='api_posshif_tenant__c37ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='possale',
            index=models.Index(fields=['tenant', 'status'], name='api_possale_tenant__928c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='possale',
            index=models.Index(fields=['tenant', 'shift'], name='api_possale_tenant__1157f8_idx'),
        ),
        migrations.AddIndex(
            model_name='possale',
            index=models.Index(fields=['tenant', 'warehouse'], name='api_possale_tenant__117f3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='possale',
            unique_together={('tenant', 'reference')},
        ),
    ]
